### ISSUE TITLE
synonyms库链接失效

### ISSUE THREAD

**Issue by pyaixy** [KnowsCount/vue-terminal#1]
抱歉打扰了，刚刚在安装synonyms时遇到了一些问题，看了您的解决方法后，我想从下面的链接下载此文件并手动保存到本地
https://static-public.chatopera.com/ml/synonyms/words.vector.gz
但此链接目前已经失效，不知能否麻烦您发送一份。
万分感谢！

**Comment by KnowsCount** [comment]
请问如何发送？

**Comment by pyaixy** [comment]
> 请问如何发送？

可以发送到我的邮箱吗？
hdqphy@163.com
非常感谢！

**Comment by KnowsCount** [comment]
由于他有一百多兆，我是转存 Google drive 发给你的，请问可否？

**Comment by pyaixy** [comment]
已收到！非常感谢！！

**Comment by susuml** [comment]
同求一份，不知能否麻烦您给我也发送一份，万分感谢。

**Comment by KnowsCount** [comment]
已发送 Gmail 共享链接。

**Comment by sauceplus** [comment]
同求words.vector.gz，不知您可否发我一份，邮箱1029497169@qq.com

**Comment by KnowsCount** [comment]
我就把链接放这吧……

---

链接: https://pan.baidu.com/s/1f-VszdwbNfvb7P0I3gpj0g  密码: 8ekb
--来自百度网盘超级会员V2的分享

---

谷歌账号挂了，等会传。

---

你们都是怎么找到这个 repo 的？？？

**Comment by KnowsCount** [comment]
https://drive.google.com/file/d/1cSxTtPdteagjKAnSjt0M4Ok-I7jOsMc4/view?usp=sharing
